name: pipeline
on:
  pull_request:
    branches:
      - main

jobs:
  verification:
    name: verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go version
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.8'
      - name: Install dependencies
        run: |
          make install-bin
          make build
          make mock
          make test
